# Generated by Django 4.2.7 on 2023-11-28 16:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('theme', models.CharField(max_length=255)),
                ('upload_date', models.DateField()),
                ('file', models.FileField(null=True, upload_to='media/lessons/')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('theme', models.CharField(max_length=255)),
                ('upload_date', models.DateField(default=datetime.date.today)),
                ('deadline', models.DateField()),
                ('file', models.FileField(null=True, upload_to='media/tasks/')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.lesson')),
            ],
        ),
    ]
